// TODO: having definitions inside an oas3 schema isn't exactly valid,
// maybe it is an idea to extract and split them into multiple oas3 schemas and reference to them.
// For now leaving as is.
export const allowedKeywords = [
	'$ref',
	'definitions',
	// From Schema
	'title',
	'multipleOf',
	'maximum',
	'exclusiveMaximum',
	'minimum',
	'exclusiveMinimum',
	'maxLength',
	'minLength',
	'pattern',
	'maxItems',
	'minItems',
	'uniqueItems',
	'maxProperties',
	'minProperties',
	'required',
	'enum',
	'type',
	'not',
	'allOf',
	'oneOf',
	'anyOf',
	'items',
	'properties',
	'additionalProperties',
	'description',
	'format',
	'default',
	'nullable',
	'discriminator',
	'readOnly',
	'writeOnly',
	'example',
	'externalDocs',
	'deprecated',
	'xml',
];
